//
//  Constant.swift
//  JMPCSchoolAppAssign17
//
//  Created by Rahul Adepu on 11/11/23.
//

import SwiftUI

struct Constant {
    static let DOEHighSchoolDirectory2017Endpoint = "https://data.cityofnewyork.us/resource/s3k6-pzi2.json"
    static let SATResultsEndpoint = "https://data.cityofnewyork.us/resource/f9bf-2cp4.json"
    
    static let previewSchoolModel:[SchoolModel] = 
    [
        SchoolModel(
            id: "02M260",
            school_name: "Clinton School Writers & Artists, M.S. 260",
            overview_paragraph: "Students who are prepared for college must have an education that encourages them to take risks as they produce and perform. Our college preparatory curriculum develops writers and has built a tight-knit community. Our school develops students who can think analytically and write creatively. Our arts programming builds on our 25 years of experience in visual, performing arts and music on a middle school level. We partner with New Audience and the Whitney Museum as cultural partners. We are a International Baccalaureate (IB) candidate school that offers opportunities to take college courses at neighboring universities.",
            academicopportunities: ["Free college courses at neighboring universities",
                                    "International Travel, Special Arts Programs, Music, Internships, College Mentoring English Language Learner Programs: English as a New Language"],
            requirement: ["Course Grades: English (87-100), Math (83-100), Social Studies (90-100), Science (88-100)",
                         ],
            admissionspriority: ["Standardized Test Scores: English Language Arts (2.8-4.5), Math (2.8-4.5)"],
            ell_programs: "",
            language_classes: "",
            advancedplacement_courses: "",
            diplomaendorsements: "",
            neighborhood: "",
            campus_name: "",
            building_code: "",
            phone_number: "212-524-4360",
            fax_number: "212-524-4365",
            school_email: "admissions@theclintonschool.net",
            website: "www.theclintonschool.net",
            primary_address_line_1: "10 East 15th Street",
            city: "Manhattan",
            state_code: "NY",
            zip: "10003",
            finalgrades: "",
            total_students: "",
            start_time: "8am",
            end_time: "3:36pm",
            extracurricular_activities: "CUNY College Now, Technology, Model UN, Student Government, School Leadership Team, Music, School Musical, National Honor Society, The Clinton Post (School Newspaper), Clinton Soup (Literary Magazine), GLSEN, Glee",
            psal_sports_boys: "",
            psal_sports_girls: "",
            psal_sports_coed: "",
            school_sports: "",
            graduation_rate: "",
            attendance_rate: "",
            college_career_rate: "")
    ]
    
    static let previewSchoolDetailModel:[SchoolDetailModel] =
    [
        SchoolDetailModel(
            id: "02M260",
            schoolName: "Clinton School Writers & Artists, M.S. 260",
            numSatTestTakers: "29",
            criticalReadingScore: "355",
            mathScore: "404",
            writingScore: "363")
    ]
}

/*
 {
 "dbn":"02M260",
 "school_name":"Clinton School Writers & Artists, M.S. 260",
 "boro":"M",
 "overview_paragraph":"Students who are prepared for college must have an education that encourages them to take risks as they produce and perform. Our college preparatory curriculum develops writers and has built a tight-knit community. Our school develops students who can think analytically and write creatively. Our arts programming builds on our 25 years of experience in visual, performing arts and music on a middle school level. We partner with New Audience and the Whitney Museum as cultural partners. We are a International Baccalaureate (IB) candidate school that offers opportunities to take college courses at neighboring universities.",
 "school_10th_seats":"1",
 "academicopportunities1":"Free college courses at neighboring universities",
 "academicopportunities2":"International Travel, Special Arts Programs, Music, Internships, College Mentoring English Language Learner Programs: English as a New Language",
 "ell_programs":"English as a New Language",
 "neighborhood":"Chelsea-Union Sq",
 "building_code":"M868",
 "location":"10 East 15th Street, Manhattan NY 10003 (40.736526, -73.992727)",
 "phone_number":"212-524-4360",
 "fax_number":"212-524-4365",
 "school_email":"admissions@theclintonschool.net",
 "website":"www.theclintonschool.net",
 "subway":"1, 2, 3, F, M to 14th St - 6th Ave; 4, 5, L, Q to 14th St-Union Square; 6, N, R to 23rd St",
 "bus":"BM1, BM2, BM3, BM4, BxM10, BxM6, BxM7, BxM8, BxM9, M1, M101, M102, M103, M14A, M14D, M15, M15-SBS, M2, M20, M23, M3, M5, M7, M8, QM21, X1, X10, X10B, X12, X14, X17, X2, X27, X28, X37, X38, X42, X5, X63, X64, X68, X7, X9",
 "grades2018":"6-11",
 "finalgrades":"6-12",
 "total_students":"376",
 "extracurricular_activities":"CUNY College Now, Technology, Model UN, Student Government, School Leadership Team, Music, School Musical, National Honor Society, The Clinton Post (School Newspaper), Clinton Soup (Literary Magazine), GLSEN, Glee",
 "school_sports":"Cross Country, Track and Field, Soccer, Flag Football, Basketball",
 "attendance_rate":"0.970000029",
 "pct_stu_enough_variety":"0.899999976",
 "pct_stu_safe":"0.970000029",
 "school_accessibility_description":"1",
 "directions1":"See theclintonschool.net for more information.",
 "requirement1_1":"Course Grades: English (87-100), Math (83-100), Social Studies (90-100), Science (88-100)",
 "requirement2_1":"Standardized Test Scores: English Language Arts (2.8-4.5), Math (2.8-4.5)",
 "requirement3_1":"Attendance and Punctuality",
 "requirement4_1":"Writing Exercise",
 "requirement5_1":"Group Interview (On-Site)","offer_rate1":"Â—57% of offers went to this group",
 "program1":"M.S. 260 Clinton School Writers & Artists","code1":"M64A",
 "interest1":"Humanities & Interdisciplinary",
 "method1":"Screened",
 "seats9ge1":"80",
 "grade9gefilledflag1":"Y",
 "grade9geapplicants1":"1515",
 "seats9swd1":"16",
 "grade9swdfilledflag1":"Y",
 "grade9swdapplicants1":"138",
 "seats101":"YesÂ–9",
 "admissionspriority11":"Priority to continuing 8th graders",
 "admissionspriority21":"Then to Manhattan students or residents",
 "admissionspriority31":"Then to New York City residents",
 "grade9geapplicantsperseat1":"19",
 "grade9swdapplicantsperseat1":"9",
 "primary_address_line_1":"10 East 15th Street",
 "city":"Manhattan",
 "zip":"10003",
 "state_code":"NY",
 "latitude":"40.73653",
 "longitude":"-73.9927",
 "community_board":"5",
 "council_district":"2",
 "census_tract":"52",
 "bin":"1089902",
 "bbl":"1008420034",
 "nta":"Hudson Yards-Chelsea-Flatiron-Union Square",
 "borough":"MANHATTAN"}
 
 
 {"dbn":"27Q475",
 "school_name":"Richmond Hill High School",
 "boro":"Q",
 "overview_paragraph":"Through a college preparatory curriculum, our school focuses on the crucial life skills of problem-solving, critical thinking, and literacy. Our school meets all studentsÂ’ educational needs, beginning with the Ninth Grade Academy and continuing with focused Small Learning Communities. Each program fosters high expectations and academic achievement in a positive and supportive learning environment. The Small Learning Community pathways include themed programs for college and career readiness. We welcome our students and parents to join us in cultivating a professional learning community.",
 "school_10th_seats":"1",
 "academicopportunities1":"Through the Business Pathway, students can graduate with MOS certification, earn SUNY and CUNY college credits and intern with top NYC firms.",
 "academicopportunities2":"The CFI program allows students to apply scientific approaches to real world scenarios and learn about careers in Forensic Science & Criminalistics",
 "academicopportunities3":"The Health Careers Pathway prepares students for College and Career Readiness in the field of Health Sciences through hands-on projects and inquiry.",
 "academicopportunities4":"The International Academy is a dynamic community of ELL's from over 30 countries taking courses intended to prepare them to be College/Career ready.",
 "academicopportunities5":"The Law Pathway educates students about the law and its applications while empowering them with the skills needed for careers in the legal field.",
 "ell_programs":"English as a New Language; Transitional Bilingual Education: Spanish",
 "language_classes":"Spanish",
 "advancedplacement_courses":"AP Biology, AP Calculus, AP English, AP Spanish",
 "neighborhood":"Richmond Hill",
 "building_code":"Q475",
 "location":"89-30 114th Street, Richmond Hill NY 11418 (40.695171, -73.833815)",
 "phone_number":"718-846-3335",
 "fax_number":"718-847-0980",
 "school_email":"contact@richmondhillhs.org",
 "website":"www.richmondhillhs.org",
 "subway":"J to 111th St; Z to 121st St",
 "bus":"Q10, Q24, Q37, Q55, Q56, Q8, QM18",
 "grades2018":"9-12",
 "finalgrades":"9-12",
 "total_students":"1950",
 "start_time":"8am",
 "end_time":"3:36pm",
 "addtl_info1":"College Trips; Community School; Extended Day Program; Health Center; Internships; Online Grading System; Saturday Programs; Student/Parent Orientation; Summer Internships; Summer Orientation",
 "extracurricular_activities":"Clubs: Law, Anime, Art, Coding, Key Club, Beautification, Horticultural, Drama, Red Cross, Book Club, Step Team, Mock Trial, Wellness Through Fitness. Service: Leadership, ARISTA, Peer Mediation, March of Dimes Walk, Student Government, Health Occupations Students of America (HOSA), Young MenÂ’s & WomenÂ’s Leadership, Ambassador Program, Breast Cancer Walk. Yearbook, Art/Music Fair, Fashion/Talent Show, Sports Night, Pep Rallies, After-School Tutoring & Regents Prep, SAT Prep, SAYA!, SASF",
 "psal_sports_boys":"Baseball, Basketball, Bowling, Handball, Indoor Track, Outdoor Track, Soccer, Swimming, Tennis, Volleyball",
 "psal_sports_girls":"Basketball, Bowling, Indoor Track, Outdoor Track, Soccer, Softball, Swimming, Tennis, Volleyball",
 "psal_sports_coed":"Cricket, Golf",
 "school_sports":"Please refer to list of PSAL activities. Additional sporting events take place through our Community Based Organizations: SAYA! and Sports and Arts Foundation.",
 "graduation_rate":"0.552999973",
 "attendance_rate":"0.850000024",
 "pct_stu_enough_variety":"0.810000002",
 "college_career_rate":"0.358999997",
 "pct_stu_safe":"0.75999999",
 "prgdesc1":"Incoming ninth graders will participate in our Ninth Grade Academy, which will allow for a positive transition to a high school setting. At the end of their ninth grade year, students will choose from six career pathways for exploration.",
 "prgdesc2":"This hybrid-program allows students to study key principles of the legal field and the scientific aspects of forensics. Students engage in learning the scientific technology and lab skills related to the field of Medical Forensics and how this scientific evidence can be utilized by the court system to reinforce the foundations of the American legal system. The curriculum also emphasizes scientific, mathematical, technological, and legal research.",
 "prgdesc3":"Upon the completion of the Ninth Grade Academy, students can explore career pathways in one of the following areas: Law, Business and Finance, Forensics and Health Sciences, and Engineering.",
 "requirement1_2":"Course Grades: Math (55-100), Science (55-100)",
 "requirement2_2":"Standardized Test Scores: Math (1.7-4.5)","requirement3_2":"Attendance",
 "offer_rate1":"Â—95% of offers went to this group",
 "offer_rate2":"Â—91% of offers went to this group",
 "program1":"Ninth Grade Academy",
 "program2":"Criminology and Forensics Institute (CFI)",
 "program3":"Zoned",
 "code1":"Q35B","code2":"Q35P","code3":"Q35Z",
 "interest1":"Humanities & Interdisciplinary",
 "interest2":"Law & Government",
 "interest3":"Zoned",
 "method1":"Ed. Opt.",
 "method2":"Screened",
 "method3":"Zoned Priority",
 "seats9ge1":"110",
 "seats9ge2":"68",
 "seats9ge3":"N/A",
 "grade9gefilledflag1":"Y",
 "grade9gefilledflag2":"N",
 "grade9gefilledflag3":"N/A",
 "grade9geapplicants1":"470",
 "grade9geapplicants2":"284",
 "grade9geapplicants3":"N/A",
 "seats9swd1":"20",
 "seats9swd2":"12",
 "seats9swd3":"N/A",
 "grade9swdfilledflag1":"Y",
 "grade9swdfilledflag2":"N",
 "grade9swdfilledflag3":"N/A",
 "grade9swdapplicants1":"103",
 "grade9swdapplicants2":"36",
 "grade9swdapplicants3":"N/A",
 "seats101":"No",
 "seats102":"No",
 "seats103":"Yes",
 "admissionspriority11":"Priority to Queens students or residents",
 "admissionspriority12":"Priority to Queens students or residents",
 "admissionspriority13":"Priority to students who apply and live in the zoned area",
 "admissionspriority21":"Then to New York City residents",
 "admissionspriority22":"Then to New York City residents",
 "grade9geapplicantsperseat1":"4",
 "grade9geapplicantsperseat2":"4",
 "grade9geapplicantsperseat3":"N/A",
 "grade9swdapplicantsperseat1":"5",
 "grade9swdapplicantsperseat2":"3",
 "grade9swdapplicantsperseat3":"N/A",
 "primary_address_line_1":"89-30 114th Street",
 "city":"Richmond Hill",
 "zip":"11418",
 "state_code":"NY",
 "latitude":"40.69517",
 "longitude":"-73.8338",
 "community_board":"9",
 "council_district":"28",
 "census_tract":"124",
 "bin":"4195688",
 "bbl":"4093210001",
 "nta":"Richmond Hill",
 "borough":"QUEENS   "}
 */
