# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

project 'FirebaseUIKit'
platform :ios, '15.0'
use_frameworks!

target 'FirebaseUIKit' do
  use_frameworks!

  # Pods for FirebaseUIKit
    pod 'FirebaseUI'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'

  target 'FirebaseUIKitTests' do
    inherit! :search_paths
  end

  target 'FirebaseUIKitUITests' do
  end

end
